apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-${CIRCLE_BUILD_NUM}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: public.ecr.aws/y3a7y2o1/t3-kubed-pub-repo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5173