apiVersion: v1
kind: Service
metadata:
  name: frontend-app-service-${CIRCLE_BUILD_NUM}
spec:
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: LoadBalancer