version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1
  #aws-ecs: circleci/aws-ecs@03.2.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          path: "backend-app"
          repo: "foz-repo-01"
          tag: backend-app