version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          path: "frontend-app"
          repo: "foz-repo-01"
          tag: "test"
