version: 2.1
orbs:
  docker: circleci/docker@2.2.0
  aws-ecr: circleci/aws-ecr@8.2.1

workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          deploy: false
          path: ./backend-app
          docker-context: ./backend-app
          image: richforrester/test
          tag: backend-app

  build-image-and-push:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: foz-repo-01
          path: ./backend-app
          build-path: ./backend-app
          tag: ${CIRCLE_BUILD_NUM}
          public-registry-alias: y3a7y2o1
          public-registry: true
          