version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

workflows:
  build_and_push_image1:
    jobs:
      - aws-ecr/build-and-push-image:
          executor: aws-ecr/default
          #extra-build-args: '--compress'
          path: "backend-app"
          push-image: true
          registry-id: ${AWS_ECR_PUBLIC_ALIAS}
          repo: ${AWS_ECR_REPO_NAME}
          tag: backend-app