version: 2.1
orbs:
  docker: circleci/docker@2.2.0

workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          deploy: false
          path: ./backend-app
          build-path: ./backend-app
          #docker-context: ./backend-app
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: ${CIRCLE_BUILD_NUM}
          update-description: true
    

  # build-docker-image-only-with-buildkit:
  #   jobs:
  #     - docker/publish:
  #         image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
  #         remote-docker-version: 20.10.12
  #         update-description: true
  #         use-buildkit: true
  #         use-remote-docker: true
