apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: public.ecr.aws/y3a7y2o1/t3-kubed-pub-repo:backend-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080