apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: 647473782560.ecr.eu-west-2.amazonaws.com/backend-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080