apiVersion: v1
kind: Service
metadata:
  name: backend-app-service-${CIRCLE_BUILD_NUM}
spec:
  selector:
    app: backend-app  
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer